---
title: "EDA"
author: "Yifei Yu"
date: "2024-10-04"
output: github_document
---

```{r}
library(tidyverse) 
```

Import the weather data

```{r} 
weather_df = 
  read_csv("weather_df.csv") |> 
  filter(
    id %in% c("USW00094728", "USW00022534", "USS0023B17S"), 
    
    date >= "2021-01-01", 
    date <= "2022-12-31"
  ) |> 
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin,
    tmax = tmax,
    month = floor_date(date, unit = "month")) |> 
  select(name, id, date, prcp, tmin, tmax, month) 
```


Let's make some plots

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

```{r}
weather_df |> 
  filter(prcp > 1000)
```


```{r}
weather_df |> 
  filter(tmax > 20, tmax < 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```


## group_by()

```{r}
weather_df |> 
  group_by(name)

#  group_by(name, month)
```



counting stuff

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(n_obs = n(),
            n_dist = n_distinct(month))
```

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(n_obs = n())
```


```{r}
weather_df |> 
  count(name)
```




## 2x2

```{r}
weather_df |> 
  drop_na(tmax) |> 
  filter(name != "Molokai_HI") |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  ) |> 
  group_by(name, cold) |> 
  summarize(count = n())
```


```{r}
weather_df |> 
  drop_na(tmax) |> 
  filter(name != "Molokai_HI") |> 
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not_cold"
    )
  ) |> 
  janitor::tabyl(name, cold)
```


## general numeric summaries.







