---
title: "Vis I"
author: "Yifei Yu"
date: "2024-10-04"
output: github_document
---

```{r}
library(tidyverse)
```

Import the weather data

```{r}
weather_df = 
  read_csv("weather_df.csv") |> 
  filter(
    id %in% c("USW00094728", "USW00022534", "USS0023B17S"), 
    
    date >= "2021-01-01", 
    date <= "2022-12-31"
  ) |> 
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin,
    tmax = tmax) |>
  select(name, id, date, prcp, tmin, tmax) 
```


Making our first plot.

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Check why some rows are missing.

```{r}
weather_df |> 
  filter(is.na(tmax))
##is this missing
```



## Fancier scatterplots!

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, colour = name)) +
  geom_point(alpha = .3, size = .8) + 
  geom_smooth(se = FALSE)

### adding alpha is to make the plot more transparent
### size makes the points look smaller
### three smooth curves
```


Where you define aesthetics can matter

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .3, size = .8) + 
  geom_smooth(se = FALSE)

### Only one smooth curve
```


Use faceting real quick

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, colour = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

### . means everything
### facet_grid(name ~ .) reverse the graph
```


Let's make a somewhat more interesting scatterplot

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```


## Learning Assessment

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax_fahr = tmax*(9/5) +32 ,
    tmin_fahr = tmin*(9/5) +32
  ) |> 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE)
```



